#! /bin/bash
rm main
rm main.zip
#GOOS=linux GOARCH=amd64 /usr/local/opt/go/libexec/bin/go build -o main main.go
#GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main main.go
GOOS=linux GOARCH=amd64 go build -o main main.go
zip -r main ./